### PR TITLE
Work around JuliaLang/julia#34121 and Release 0.7.1

### PR DESCRIPTION
**Pull request by kimikage**
This backports PR #160.

### CODE REVIEW

**Comment by kimikage** [comment]
BTW, it might be a good idea to protect the `release-*` branches.

**Comment by timholy** [comment]
Looks like `master` is still on 0.7.0?

**Comment by kimikage** [comment]
I haven't yet rewrote the version number because in FixedPointNumbers.jl, it was a habit to rewrite the version number just before release, not just after release. However, we may want to use v0.8.0 (or v0.7.1) now to clarify the order.

**Comment by timholy** [comment]
In general, I only use release branches if I want to make further releases in an older release cycle. Otherwise I just release from `master`.

**Comment by kimikage** [comment]
We already have the some commits with breaking changes, i.e. v0.7 is already in an old release cycle.

**Pull request merged**
