### PR TITLE
fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

### PR DESCRIPTION
**Pull request by Sacha0**
Best! :)

### CODE REVIEW

**Comment by lobingera** [comment]
@Sacha0 Should this run on a recent 0.7 (Version 0.7.0-DEV.1245 (2017-08-05 05:18 UTC)?
I just merged the PR locally and got:
```
julia> using FixedPointNumbers
INFO: Precompiling module FixedPointNumbers.

WARNING: deprecated syntax "parametric method syntax reinterpret{T, f}(::Type{T}, x::FixedPoint{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:42".
Use "reinterpret(#unused#::Type{T}, x::FixedPoint{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax *{X <: FixedPoint}(x::Real, ::Type{X}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:45".
Use "*(x::Real, #unused#::Type{X}) where X <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax =={T <: FixedPoint}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:48".
Use "==(x::T, y::T) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax <{T <: FixedPoint}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:49".
Use "<(x::T, y::T) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax <={T <: FixedPoint}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:50".
Use "<=(x::T, y::T) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax isapprox{T <: FixedPoint}(x::T, y::T; rtol = 0, atol = max(eps(x), eps(y))) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:57".
Use "isapprox(x::T, y::T; rtol = 0, atol = max(eps(x), eps(y))) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax isinteger{T, f}(x::FixedPoint{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:66".
Use "isinteger(x::FixedPoint{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax typemax{T <: FixedPoint}(::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:69".
Use "typemax(#unused#::Type{T}) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax typemin{T <: FixedPoint}(::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:70".
Use "typemin(#unused#::Type{
WARNING: deprecated syntax "parametric method syntax realmin{T <: FixedPoint}(::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:71".
Use "realmin(#unused#::Type{T}) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax realmax{T <: FixedPoint}(::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:72".
Use "realmax(#unused#::Type{T}) where T <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax floattype{T <: ShortInts, f}(::Type{FixedPoint{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:87".
Use "floattype(#unused#::Type{FixedPoint{T, f}}) where {T <: ShortInts, f}" instead.

WARNING: deprecated syntax "parametric method syntax floattype{T <: Integer, f}(::Type{FixedPoint{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:88".
Use "floattype(#unused#::Type{FixedPoint{T, f}}) where {T <: Integer, f}" instead.

WARNING: deprecated syntax "parametric method syntax floattype{F <: FixedPoint}(::Type{F}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:89".
Use "floattype(#unused#::Type{F}) where F <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax nbitsfrac{T <: Integer, f}(::Type{FixedPoint{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:92".
Use "nbitsfrac(#unused#::Type{FixedPoint{T, f}}) where {T <: Integer, f}" instead.

WARNING: deprecated syntax "parametric method syntax nbitsfrac{F <: FixedPoint}(::Type{F}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:93".
Use "nbitsfrac(#unused#::Type{F}) where F <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax rawtype{T <: Integer, f}(::Type{FixedPoint{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:95".
Use "rawtype(#unused#::Type{FixedPoint{T, f}}) where {T <: Integer, f}" instead.

WARNING: deprecated syntax "parametric method syntax rawtype{F <: FixedPoint}(::Type{F}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:96".
Use "rawtype(#unused#::Type{F}) where F <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax showtype{X <: FixedPoint}(io::IO, ::Type{X}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:105".
Use "showtype(io::IO, #unused#::Type{X}) where X <: FixedPoint" instead.

WARNING: deprecated syntax "parametric method syntax show{T, f}(io::IO, x::FixedPoint{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:112".
Use "show(io::IO, x::FixedPoint{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax showcompact{T, f}(io::IO, x::FixedPoint{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:116".
Use "showcompact(io::IO, x::FixedPoint{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax ::Type{Fixed{T, f}}{T, f}(i::Integer, _) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:7".
Use "false(i::Integer, _) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax ::Type{Fixed{T, f}}{T, f}(x) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:8".T}) where T <: FixedPoint" instead.

Use "false(x) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax reinterpret{T <: Signed, f}(::Type{Fixed{T, f}}, x::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:11".
Use "reinterpret(#unused#::Type{Fixed{T, f}}, x::T) where {T <: Signed, f}" instead.

WARNING: deprecated syntax "parametric method syntax typechar{X <: Fixed}(::Type{X}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:13".
Use "typechar(#unused#::Type{X}) where X <: Fixed" instead.

WARNING: deprecated syntax "parametric method syntax signbits{X <: Fixed}(::Type{X}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:14".
Use "signbits(#unused#::Type{X}) where X <: Fixed" instead.

WARNING: deprecated syntax "parametric method syntax -{T, f}(x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:27".
Use "-(x::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax abs{T, f}(x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:28".
Use "abs(x::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax +{T, f}(x::Fixed{T, f}, y::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:30".
Use "+(x::Fixed{T, f}, y::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax -{T, f}(x::Fixed{T, f}, y::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:31".
Use "-(x::Fixed{T, f}, y::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax *{T, f}(x::Fixed{T, f}, y::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:36".
Use "*(x::Fixed{T, f}, y::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax /{T, f}(x::Fixed{T, f}, y::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:38".
Use "/(x::Fixed{T, f}, y::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{T, f}(::Type{Fixed{T, f}}, x::Integer) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:42".
Use "convert(#unused#::Type{Fixed{T, f}}, x::Integer) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{T, f}(::Type{Fixed{T, f}}, x::AbstractFloat) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:43".
Use "convert(#unused#::Type{Fixed{T, f}}, x::AbstractFloat) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{T, f}(::Type{Fixed{T, f}}, x::Rational) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:44".
Use "convert(#unused#::Type{Fixed{T, f}}, x::Rational) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax rem{T, f}(x::Integer, ::Type{Fixed{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:46".
Use "rem(x::Integer, #unused#::Type{Fixed{T, f}}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax rem{T, f}(x::Real, ::Type{Fixed{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:47".
Use "rem(x::Real, #unused#::Type{Fixed{T, f}}) where {T, f}" instead.
WARNING: deprecated syntax "parametric method syntax convert{T, f}(::Type{BigFloat}, x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:52".
Use "convert(#unused#::Type{BigFloat}, x::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{TF <: AbstractFloat, T, f}(::Type{TF}, x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:54".
Use "convert(#unused#::Type{TF}, x::Fixed{T, f}) where {TF <: AbstractFloat, T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{T, f}(::Type{Bool}, x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:57".
Use "convert(#unused#::Type{Bool}, x::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{T, f}(::Type{Integer}, x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:59".
Use "convert(#unused#::Type{Integer}, x::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{TI <: Integer, T, f}(::Type{TI}, x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:63".
Use "convert(#unused#::Type{TI}, x::Fixed{T, f}) where {TI <: Integer, T, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{TR <: Rational, T, f}(::Type{TR}, x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:67".
Use "convert(#unused#::Type{TR}, x::Fixed{T, f}) where {TR <: Rational, T, f}" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T, f, TI <: Integer}(ft::Type{Fixed{T, f}}, ::Type{TI}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:70".
Use "promote_rule(ft::Type{Fixed{T, f}}, #unused#::Type{TI}) where {T, f, TI <: Integer}" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T, f, TF <: AbstractFloat}(::Type{Fixed{T, f}}, ::Type{TF}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:71".
Use "promote_rule(#unused#::Type{Fixed{T, f}}, #unused#::Type{TF}) where {T, f, TF <: AbstractFloat}" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T, f, TR}(::Type{Fixed{T, f}}, ::Type{Rational{TR}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:72".
Use "promote_rule(#unused#::Type{Fixed{T, f}}, #unused#::Type{Rational{TR}}) where {T, f, TR}" instead.

WARNING: deprecated syntax "parametric method syntax decompose{T, f}(x::Fixed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:75".
Use "decompose(x::Fixed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax ::Type{Normed{T, f}}{T, f}(i::Integer, _) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:7".
Use "false(i::Integer, _) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax ::Type{Normed{T, f}}{T, f}(x) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:8".
Use "false(x) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax typechar{X <: Normed}(::Type{X}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:11".
Use "typechar(#unused#::Type{X}) where X <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax signbits{X <: Normed}(::Type{X}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:12".
Use "signbits(#unused#::Type{X}) where X <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax reinterpret{T <: Unsigned, f}(::Type{Normed{T, f}}, x::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:24".
Use "reinterpret(#unused#::Type{Normed{T, f}}, x::T) where {T <: Unsigned, f}" instead.

WARNING: deprecated syntax "parametric method syntax zero{T, f}(::Type{Normed{T, f}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:26".
Use "zero(#unused#::Type{Normed{T, f}}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax one{T <: Normed}(::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:28".
Use "one(#unused#::Type{T}) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax convert{U <: Normed}(::Type{U}, x::U) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:35".
Use "convert(#unused#::Type{U}, x::U) where U <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax convert{T1 <: Unsigned, T2 <: Unsigned, f}(::Type{Normed{T1, f}}, x::Normed{T2, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:36".
Use "convert(#unused#::Type{Normed{T1, f}}, x::Normed{T2, f}) where {T1 <: Unsigned, T2 <: Unsigned, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{T <: Unsigned, T2 <: Unsigned, f}(::Type{Normed{T, f}}, x::Normed{T2}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:38".
Use "convert(#unused#::Type{Normed{T, f}}, x::Normed{T2}) where {T <: Unsigned, T2 <: Unsigned, f}" instead.

WARNING: deprecated syntax "parametric method syntax convert{U <: Normed}(::Type{U}, x::Real) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:43".
Use "convert(#unused#::Type{U}, x::Real) where U <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax _convert{U <: Normed, T}(::Type{U}, ::Type{T}, x) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:47".
Use "_convert(#unused#::Type{U}, #unused#::Type{T}, x) where {U <: Normed, T}" instead.

WARNING: deprecated syntax "parametric method syntax _convert{U <: Normed}(::Type{U}, ::Type{UInt128}, x) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:52".
Use "_convert(#unused#::Type{U}, #unused#::Type{UInt128}, x) where U <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax rem{T <: Normed}(x::T, ::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:57".
Use "rem(x::T, #unused#::Type{T}) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax rem{T <: Normed}(x::Normed, ::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:58".
Use "rem(x::Normed, #unused#::Type{T}) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax rem{T <: Normed}(x::Real, ::Type{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:59".
Use "rem(x::Real, #unused#::Type{T}) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax convert{T <: AbstractFloat}(::Type{T}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:66".
Use "convert(#unused#::Type{T}, x::Normed) where T <: AbstractFloat" instead.

WARNING: deprecated syntax "parametric method syntax convert{T <: Integer}(::Type{T}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:71".
Use "convert(#unused#::Type{T}, x::Normed) where T <: Integer" instead.

WARNING: deprecated syntax "parametric method syntax convert{Ti <: Integer}(::Type{Rational{Ti}}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:72".
Use "convert(#unused#::Type{Rational{Ti}}, x::Normed) where Ti <: Integer" instead.

WARNING: deprecated syntax "parametric method syntax -{T <: Normed}(x::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:78".
Use "-(x::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax ~{T <: Normed}(x::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:79".
Use "~(x::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax +{T, f}(x::Normed{T, f}, y::Normed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:81".
Use "+(x::Normed{T, f}, y::Normed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax -{T, f}(x::Normed{T, f}, y::Normed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:82".
Use "-(x::Normed{T, f}, y::Normed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax *{T <: Normed}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:83".
Use "*(x::T, y::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax /{T <: Normed}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:84".
Use "/(x::T, y::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax <{T <: Normed}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:87".
Use "<(x::T, y::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax <={T <: Normed}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:88".
Use "<=(x::T, y::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax trunc{T <: Normed}(x::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:91".
Use "trunc(x::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax floor{T <: Normed}(x::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:92".
Use "floor(x::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax round{T, f}(x::Normed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:94".
Use "round(x::Normed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax ceil{T, f}(x::Normed{T, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:100".
Use "ceil(x::Normed{T, f}) where {T, f}" instead.

WARNING: deprecated syntax "parametric method syntax trunc{T <: Integer}(::Type{T}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:107".
Use "trunc(#unused#::Type{T}, x::Normed) where T <: Integer" instead.

WARNING: deprecated syntax "parametric method syntax round{T <: Integer}(::Type{T}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:108".
Use "round(#unused#::Type{T}, x::Normed) where T <: Integer" instead.

WARNING: deprecated syntax "parametric method syntax floor{T <: Integer}(::Type{T}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:109".
Use "floor(#unused#::Type{T}, x::Normed) where T <: Integer" instead.

WARNING: deprecated syntax "parametric method syntax ceil{T <: Integer}(::Type{T}, x::Normed) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:110".
Use "ceil(#unused#::Type{T}, x::Normed) where T <: Integer" instead.

WARNING: deprecated syntax "parametric method syntax bswap{f}(x::Normed{UInt8, f}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:116".
Use "bswap(x::Normed{UInt8, f}) where f" instead.

WARNING: deprecated syntax "parametric method syntax minmax{T <: Normed}(x::T, y::T) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:120".
Use "minmax(x::T, y::T) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax start{T <: Normed}(r::StepRange{T}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:127".
Use "start(r::StepRange{T}) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax next{T <: Normed}(r::StepRange{T}, i::Integer) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:128".
Use "next(r::StepRange{T}, i::Integer) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax done{T <: Normed}(r::StepRange{T}, i::Integer) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:130".
Use "done(r::StepRange{T}, i::Integer) where T <: Normed" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T <: Normed, Tf <: AbstractFloat}(::Type{T}, ::Type{Tf}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:140".
Use "promote_rule(#unused#::Type{T}, #unused#::Type{Tf}) where {T <: Normed, Tf <: AbstractFloat}" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T <: Normed, R <: Rational}(::Type{T}, ::Type{R}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:141".
Use "promote_rule(#unused#::Type{T}, #unused#::Type{R}) where {T <: Normed, R <: Rational}" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T <: Normed, Ti <: Union{Signed, Unsigned}}(::Type{T}, ::Type{Ti}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:143".
Use "promote_rule(#unused#::Type{T}, #unused#::Type{Ti}) where {T <: Normed, Ti <: Union{Signed, Unsigned}}" instead.

WARNING: deprecated syntax "parametric method syntax promote_rule{T1, T2, f1, f2}(::Type{Normed{T1, f1}}, ::Type{Normed{T2, f2}}) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:146".
Use "promote_rule(#unused#::Type{Normed{T1, f1}}, #unused#::Type{Normed{T2, f2}}) where {T1, T2, f1, f2}" instead.

WARNING: deprecated syntax "parametric method syntax _unsafe_trunc{T}(::Type{T}, x::Integer) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:158".
Use "_unsafe_trunc(#unused#::Type{T}, x::Integer) where T" instead.

WARNING: deprecated syntax "parametric method syntax _unsafe_trunc{T}(::Type{T}, x) around /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:159".
Use "_unsafe_trunc(#unused#::Type{T}, x) where T" instead.
ERROR: LoadError: LoadError: TypeError: in @deprecate, in typeassert, expected Symbol, got Expr
Stacktrace:
 [1] include_relative(::Module, ::String) at ./loading.jl:464
 [2] include at ./sysimg.jl:14 [inlined]
 [3] include(::String) at /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl:3
 [4] include_relative(::Module, ::String) at ./loading.jl:464
 [5] include(::Module, ::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/lobi/.julia/v0.7/FixedPointNumbers/src/deprecations.jl, in expression starting on line 31
while loading /home/lobi/.julia/v0.7/FixedPointNumbers/src/FixedPointNumbers.jl, in expression starting on line 121
ERROR: Failed to precompile FixedPointNumbers to /home/lobi/.julia/lib/v0.7/FixedPointNumbers.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:598
 [2] _require(::Symbol) at ./loading.jl:407
 [3] require(::Symbol) at ./loading.jl:318

```

**Comment by timholy** [comment]
These are new deprecations, and I don't think the failure has anything to do with this.

**Comment by Sacha0** [comment]
Thanks Tim! :)

**Comment by lobingera** [comment]
@timholy, just to confirm, i downgraded my local julia to Version 0.7.0-DEV.1165 (2017-07-31 03:33 UTC), Commit 1a43098* (6 days old master) and then master/this passes.

**Comment by timholy** [comment]
See #89

**Pull request merged**
