### PR TITLE
Indent testsets

### PR DESCRIPTION
**Pull request by scls19fr**
It helps a lot reading

### CODE REVIEW

**Comment by timholy** [comment]
It's a good idea. I might wait until @RalphAS's PRs are in (#113 and #115), if that's OK with you.

**Comment by scls19fr** [comment]
Merge conflicts should be resolved here

**Comment by timholy** [comment]
There's some syntax error, however.

**Comment by scls19fr** [comment]
Travis CI looks good now... but AppVeyor is pending

**Comment by timholy** [comment]
> but AppVeyor is pending

There are too many packages running under my AppVeyor account. I tried clearing a few but it will be a while yet. Sorry for the delay.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
